# Generated by Django 2.2.1 on 2019-05-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='TICKER',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='responses',
            name='BETA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='responses',
            name='CAPM',
            field=models.FloatField(),
        ),
    ]
